language: python

python:
  - 3.8
  - 3.7
  - 3.6

env:
  - DJANGO=2.2
  - DJANGO=2.1
  - DJANGO=2.0
  - DJANGO=1.11

install:
  - pip install -r "test_requirements/django-$DJANGO.txt"

script:
  - pep8 fancy_cronfield
  - coverage run --branch --parallel-mode setup.py test
  - coverage combine
  - coverage xml -o coverage.xml

after_success:
  - codecov
