language: python

python:
  - 2.7
  - 2.6

env:
  - DJANGO=1.5

install:
  - pip install -r "test_requirements/django-$DJANGO.txt"
  - pip install pep8

script:
  - pep8 fancy_cronfield
  - python setup.py test

notifications:
  irc:
    - irc.freenode.org#django-fancy-cronfield