language: python

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

env:
  - DJANGO=1.8
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5

install:
  - pip install -r "test_requirements/django-$DJANGO.txt"
  - pip install pep8

script:
  - pep8 fancy_cronfield
  - coverage run --parallel-mode setup.py test
  - coverage combine

after_success: coveralls

notifications:
  irc:
    - irc.freenode.org#django-fancy-cronfield

matrix:
  exclude:

    - python: 2.6
      env: DJANGO=1.7
    - python: 2.6
      env: DJANGO=1.8
    - python: 3.5
      env: DJANGO=1.5
    - python: 3.5
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.7

  allow_failures:
    - python: 3.5
      env: DJANGO=1.9